version: '3'

services:
  frontend:
    stdin_open: true
    build: ./react-todo-postgres
    ports:
      - "3000:3000"
    volumes:
      - ./react-todo-postgres/:/usr/src/fe/app

  backend:
    build: ./node-todo-postgres
    ports:
    - "5000:5000"
    volumes:
    - ./node-todo-postgres/:/usr/src/be/app
